sudo: required
services:
  - docker

before_install:
  - docker build -t ancosta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ancosta/react-test npm test -- --coverage

after_success:
  - docker build -t ancosta/multi-client ./client
  - docker build -t ancosta/multi-nginx ./nginx
  - docker build -t ancosta/multi-server ./server
  - docker build -t ancosta/multi-worker ./worker
